#!/usr/bin/env python3
"""
Organize 365 tracks into phase-based directory structure matching the OS boot concept:
- DIRECTORY A: /BOOT_SEQUENCE (Days 1-83)
- DIRECTORY B: /CACHE_OVERFLOW (Days 84-187)
- DIRECTORY C: /ROOT_ACCESS (Days 188-271)
- DIRECTORY D: /THE_CLOUD (Days 272-365)
"""

import os
import shutil
from pathlib import Path

# Configuration
TEMP_MUSIC = Path("/Volumes/extremeUno/temp_music")
OUTPUT_BASE = Path("365-releases/audio")

# Complete song list organized by phase
SONGS = {
    # DIRECTORY A: /BOOT_SEQUENCE (Days 1-83)
    "BOOT_SEQUENCE": [
        (1, "Were Going Crazy World"),
        (2, "Shhh Bitch"),
        (3, "You Like Steve Earle"),
        (4, "Were Only Humanmd7"),
        (5, "Swooped COUPE"),
        (6, "Ss Take One"),
        (7, "Devour"),
        (8, "Poetry"),
        (9, "Without You"),
        (10, "PERMISSION_DENIED [LOG_108]"),
        (11, "Getting Better"),
        (12, "LANDR Want It Any Other Way Open Low"),
        (13, "Dashboard of Life"),
        (14, "Undercoa 4"),
        (15, "What Bryan Was Working on Last"),
        (16, "Prevail Scriber"),
        (17, "What It Is"),
        (18, "Goods 4 Me"),
        (19, "Through the Ringer"),
        (20, "Figures"),
        (21, "Highup"),
        (22, "REBOOT_SEQUENCE [LOG_109]"),
        (23, "Come on Dance"),
        (24, "Be Here Boo"),
        (25, "Grenada"),
        (26, "Brave"),
        (27, "Talkin Nody"),
        (28, "LANDR Smoothie Balanced Medium"),
        (29, "Cursed 2ndmix"),
        (30, "To Be a Man"),
        (31, "Scars in My Mind"),
        (32, "Whatuwant"),
        (33, "Bettersion of Me"),
        (34, "Consation W"),
        (35, "The Light"),
        (36, "404_SOUL_NOT_FOUND [LOG_101]"),
        (37, "Camebackaroudnd"),
        (38, "Eco N Time"),
        (39, "Up All Night"),
        (40, "Way Eight Fore Dat Storm Level"),
        (41, "Be Nuter"),
        (42, "Xzibit Forever"),
        (43, "Pit What I Got"),
        (44, "Not Good Enough"),
        (45, "LANDR a Way Out Mas Balanced Medium"),
        (46, "Mikeym"),
        (47, "Filthy"),
        (48, "Unforgettable"),
        (49, "Dreams Again"),
        (50, "DAEMON_RUNNING [LOG_102]"),
        (51, "Change Perception"),
        (52, "Bitter Better"),
        (53, "The End"),
        (54, "Tryied"),
        (55, "Tried N True"),
        (56, "Can't Go Back"),
        (57, "Momentofexctasy"),
        (58, "Awaits"),
        (59, "Reality"),
        (60, "Moment of Exctasy"),
        (61, "Re"),
        (62, "Friendzone"),
        (63, "Never Ends"),
        (64, "CONNECTION_RESET [LOG_100]"),
        (65, "Untied"),
        (66, "Luckyland"),
        (67, "Letitgo"),
        (68, "From the Earth to the Sea Flipped Mask"),
        (69, "Save Tonight"),
        (70, "Sau"),
        (71, "A Girl"),
        (72, "Isitthathard"),
        (73, "Kurtcobain"),
        (74, "Low Life"),
        (75, "PING_TIMEOUT [LOG_106]"),
        (76, "Benefits Me"),
        (77, "Rabbit Hole"),
        (78, "Choppmed of F Ya Feel Rough"),
        (79, "Lightburst"),
        (80, "Monetary"),
        (81, "Get Ghost"),
        (82, "ADMIN_ACCESS_REQUIRED [LOG_107]"),
        (83, "Jacy B"),
    ],
    
    # DIRECTORY B: /CACHE_OVERFLOW (Days 84-187)
    "CACHE_OVERFLOW": [
        (1, "LANDR Self Dick Mas Balanced Medium"),
        (2, "Odosed"),
        (3, "Your Choice"),
        (4, "LANDR Scars in My Mind M Balanced Medium"),
        (5, "Cheat Code"),
        (6, "Peacefullypeace"),
        (7, "Killing Me"),
        (8, "UPLOADING_CONSCIOUSNESS... [LOG_134]"),
        (9, "KERNEL_PANIC [LOG_135]"),
        (10, "INSTALLING_UPDATES... [LOG_136]"),
        (11, "Pop"),
        (12, "404_SOUL_NOT_FOUND [LOG_124]"),
        (13, "Dream"),
        (14, "Cold As Ice"),
        (15, "Unifying"),
        (16, "DAEMON_RUNNING [LOG_128]"),
        (17, "LANDR Here I Go Again 1 Warm High"),
        (18, "Demon Soul"),
        (19, "ADMIN_ACCESS_REQUIRED [LOG_114]"),
        (20, "My Way"),
        (21, "LANDR Dance Floor Balanced Medium"),
        (22, "Gasp"),
        (23, "No Matter the Pain"),
        (24, "DECRYPTING_FILES... [LOG_119]"),
        (25, "UPLOADING_CONSCIOUSNESS... [LOG_138]"),
        (26, "Wish I Was Dead"),
        (27, "LANDR-stay and i go-Balanced-Medium"),
        (28, "MEMORY_LEAK [LOG_126]"),
        (29, "Double Agent"),
        (30, "One Bye One"),
        (31, "UPLOADING_CONSCIOUSNESS... [LOG_131]"),
        (32, "A Fine Sin Remix"),
        (33, "Quite the Lie 1"),
        (34, "LANDR Finding HOME Neut Balanced Medium"),
        (35, "Get High with Me"),
        (36, "END_OF_LINE [LOG_121]"),
        (37, "Self Dick"),
        (38, "Tainted Gospal"),
        (39, "SYSTEM_OVERHEAT [LOG_118]"),
        (40, "Burn It to the Ground Gapless"),
        (41, "Te Amo"),
        (42, "PING_TIMEOUT [LOG_117]"),
        (43, "Why U Lie"),
        (44, "Pure Popped"),
        (45, "TRACING_ROUTE_TO_GOD [LOG_112]"),
        (46, "Cant Escape Mas"),
        (47, "Airwaves Feat Zillick"),
        (48, "SYNTAX_ERROR_IN_LIFE [LOG_110]"),
        (49, "Oldenside of You"),
        (50, "SYNTAX_ERROR_IN_LIFE [LOG_120]"),
        (51, "Bye Bi"),
        (52, "BUFFERING_REALITY [LOG_133]"),
        (53, "Get Naughty"),
        (54, "Little Light"),
        (55, "OLB Remix 2"),
        (56, "Believing in Just"),
        (57, "Come Around Persiuin"),
        (58, "Nostic Heresy"),
        (59, "If You Come Along"),
        (60, "Come Together"),
        (61, "REBOOT_SEQUENCE [LOG_111]"),
        (62, "TRACING_ROUTE_TO_GOD [LOG_137]"),
        (63, "Grin Nada"),
        (64, "Get It in"),
        (65, "Breaking M E"),
        (66, "LANDR Burning It Down Co Balanced Medium"),
        (67, "FILE_CORRUPTED [LOG_122]"),
        (68, "PACKET_LOSS_DETECTED [LOG_130]"),
        (69, "Aborted"),
        (70, "DISK_FRAGMENTATION [LOG_123]"),
        (71, "CONNECTION_RESET [LOG_139]"),
        (72, "Fast Life"),
        (73, "Shawty Not a Hottie"),
        (74, "MEMORY_LEAK [LOG_132]"),
        (75, "Starshining"),
        (76, "On Sight"),
        (77, "FILE_CORRUPTED [LOG_113]"),
        (78, "Wishingwell"),
        (79, "PACKET_LOSS_DETECTED [LOG_125]"),
        (80, "World Ending"),
        (81, "OLB Remix"),
        (82, "LANDR This H Balanced Medium"),
        (83, "Bright Day"),
        (84, "Natural Disaster"),
        (85, "Abandon"),
        (86, "echoes.of.the.abyss.votd"),
        (87, "REBOOT_SEQUENCE [LOG_115]"),
        (88, "Addicted"),
        (89, "Left on Red"),
        (90, "SYSTEM_OVERHEAT [LOG_127]"),
        (91, "LANDR Crying Lil Bitch Balanced Medium REV"),
        (92, "Monday Ta Wenday Ta Friday"),
        (93, "Dirt Road"),
        (94, "Leave Me Dead"),
        (95, "PERMISSION_DENIED [LOG_116]"),
        (96, "Fly Away Again"),
        (97, "Malibu"),
        (98, "Loss"),
        (99, "ONE LAST Breath 3"),
        (100, "Against the Grain"),
        (101, "You're Alwats on My Mind"),
        (102, "Trippie"),
        (103, "Life Succubus"),
        (104, "Afinesin"),
    ],
    
    # DIRECTORY C: /ROOT_ACCESS (Days 188-271)
    "ROOT_ACCESS": [
        (1, "Flicker Like Fire"),
        (2, "Fundrip"),
        (3, "Sometimes"),
        (4, "MEMORY_LEAK [LOG_149]"),
        (5, "Isolkated"),
        (6, "Spaces"),
        (7, "To Myself"),
        (8, "Standing on E"),
        (9, "Buck Im Here Yto Fuck"),
        (10, "Riddle"),
        (11, "Hhhhhhhhhhhhh"),
        (12, "Surrender to U"),
        (13, "END_OF_LINE [LOG_145]"),
        (14, "Backroads"),
        (15, "LANDR Take Me Away Take Blenmd Warm Low"),
        (16, "Missing You"),
        (17, "Maybe Baby Itts on Me"),
        (18, "True Lies"),
        (19, "Find Her Demo Entire Mix"),
        (20, "4u"),
        (21, "Away Goes"),
        (22, "Emotuional Healing Mas"),
        (23, "Feel It"),
        (24, "PACKET_LOSS_DETECTED [LOG_146]"),
        (25, "Nostalgic Energby"),
        (26, "Nick Snuff M3"),
        (27, "Wasted by What"),
        (28, "What Is God Withoot Me"),
        (29, "Paid the World Back Beat"),
        (30, "LANDR If You Leave0 Open Low"),
        (31, "FILE_CORRUPTED [LOG_140]"),
        (32, "Flowers of Us"),
        (33, "Cant Have"),
        (34, "Footsteps"),
        (35, "SYNTAX_ERROR_IN_LIFE [LOG_144]"),
        (36, "FILE_CORRUPTED [LOG_147]"),
        (37, "Complicated S"),
        (38, "Speed of Pain"),
        (39, "Unloved"),
        (40, "CONNECTION_RESET [LOG_141]"),
        (41, "Faint Copy"),
        (42, "DAEMON_RUNNING [LOG_148]"),
        (43, "Live Forefeat Xzibit"),
        (44, "SYSTEM_OVERHEAT [LOG_143]"),
        (45, "Ngbt1"),
        (46, "Dreams Shattered"),
        (47, "Maybe Baby"),
        (48, "Diamond Death"),
        (49, "A Stop in Time"),
        (50, "Dont Ghost Me"),
        (51, "TRACING_ROUTE_TO_GOD [LOG_142]"),
        (52, "Poth"),
        (53, "Sicko"),
        (54, "Adrift"),
        (55, "Dark Thoughts"),
        (56, "Mystery"),
        (57, "Message 4 K Comp M1"),
        (58, "PERMISSION_DENIED [LOG_150]"),
        (59, "Hemmorage"),
        (60, "Monetary T"),
        (61, "D and D"),
        (62, "Blackout"),
        (63, "Sirens"),
        (64, "Running"),
        (65, "Fuck B"),
        (66, "Get Oyou"),
        (67, "Only Time Will Tell"),
        (68, "Far Away"),
        (69, "Hades"),
        (70, "Midnight Piano"),
        (71, "Johnny DEMON"),
        (72, "Sunset"),
        (73, "Purple Sky"),
        (74, "Darewell"),
        (75, "Alien 2nd Mix"),
        (76, "Purpose"),
        (77, "Grave Robber"),
        (78, "Too Late Fawy"),
        (79, "Clebit"),
        (80, "LANDR Hemmorage 1 Open Medium"),
        (81, "Sweater"),
        (82, "What You Know"),
        (83, "Falling Apart"),
        (84, "PULSE"),
    ],
    
    # DIRECTORY D: /THE_CLOUD (Days 272-365)
    "THE_CLOUD": [
        (1, "Say It Up"),
        (2, "Awe Ofu"),
        (3, "Outlast"),
        (4, "BUFFERING_REALITY [LOG_164]"),
        (5, "BUFFERING_REALITY [LOG_162]"),
        (6, "Starlight"),
        (7, "Prevail"),
        (8, "Hatedown"),
        (9, "Falllin"),
        (10, "Haert N Soul Collide"),
        (11, "Exhale"),
        (12, "END_OF_LINE [LOG_166]"),
        (13, "My Sacrifices"),
        (14, "KERNEL_PANIC [LOG_156]"),
        (15, "KERNEL_PANIC [LOG_158]"),
        (16, "INSTALLING_UPDATES... [LOG_163]"),
        (17, "LANDR Love for You Balanced Medium"),
        (18, "Beat 2 O"),
        (19, "No Place 2 Hide"),
        (20, "Chunky"),
        (21, "REBOOT_SEQUENCE [LOG_161]"),
        (22, "You Know You 2e"),
        (23, "Wysiwyg"),
        (24, "Sing to Me"),
        (25, "Open All Night"),
        (26, "Trip"),
        (27, "Burning It Down Comd2"),
        (28, "It Wont Take Lolng"),
        (29, "SYNTAX_ERROR_IN_LIFE [LOG_167]"),
        (30, "UPLOADING_CONSCIOUSNESS... [LOG_155]"),
        (31, "LANDR Sweet You Warm Medium"),
        (32, "ADMIN_ACCESS_REQUIRED [LOG_151]"),
        (33, "Locked Up"),
        (34, "Negonnas Stop Loving You"),
        (35, "INSTALLING_UPDATES... [LOG_154]"),
        (36, "Hard to Ignore"),
        (37, "Open Wide"),
        (38, "Be Altm"),
        (39, "It's Gonna Be Alright"),
        (40, "PING_TIMEOUT [LOG_153]"),
        (41, "Feel Good"),
        (42, "Wrap That"),
        (43, "DECRYPTING_FILES... [LOG_152]"),
        (44, "Trip Into Background"),
        (45, "Entropy"),
        (46, "Odds"),
        (47, "Go Get It"),
        (48, "Come Along with Me"),
        (49, "She Said Lil Richard Where Da Fux U"),
        (50, "Dont Blame U"),
        (51, "Yourbody"),
        (52, "ADMIN_ACCESS_REQUIRED [LOG_165]"),
        (53, "Advice 2"),
        (54, "Climax"),
        (55, "REBOOT_SEQUENCE [LOG_169]"),
        (56, "Summers Ending"),
        (57, "DAEMON_RUNNING [LOG_159]"),
        (58, "80s Stack"),
        (59, "PING_TIMEOUT [LOG_168]"),
        (60, "So Done"),
        (61, "END_OF_LINE [LOG_160]"),
        (62, "My Past"),
        (63, "You Got Me"),
        (64, "Bb"),
        (65, "404_SOUL_NOT_FOUND [LOG_157]"),
        (66, "Climb to You"),
        (67, "Basic"),
        (68, "No Service"),
        (69, "TRACING_ROUTE_TO_GOD [LOG_170]"),
        (70, "When I Say Forever"),
        (71, "LANDR Childhood Warm Low"),
        (72, "ONLY SON"),
        (73, "Beauty"),
        (74, "Climbing 2u"),
        (75, "Spippin"),
        (76, "Luckyland Reprise"),
        (77, "Alf"),
    ],
}

def create_directories():
    """Create phase directories"""
    for phase in SONGS.keys():
        phase_dir = OUTPUT_BASE / phase
        phase_dir.mkdir(parents=True, exist_ok=True)
        print(f"✓ Created: {phase_dir}")

def create_placeholder_files():
    """Create placeholder files for ERROR entries"""
    for phase, tracks in SONGS.items():
        phase_dir = OUTPUT_BASE / phase
        
        for day, song_name in tracks:
            if "LOG_" in song_name and "[" in song_name:
                # Format: NN - ERROR_TEXT [LOG_XXX].txt
                target_name = f"{day:02d} - {song_name}.txt"
                target_path = phase_dir / target_name
                target_path.write_text(f"// {song_name}\n// This is a placeholder for LOG entry\n")
                print(f"  ✓ Placeholder: {target_name}")

def main():
    print("🎵 Organizing 365 tracks into phase-based structure\n")
    
    # Create directories
    print("📁 Creating directories...")
    create_directories()
    print("")
    
    # Create placeholder files for LOG entries
    print("📝 Creating placeholder files for LOG entries...")
    create_placeholder_files()
    print("")
    
    # Print summary
    print("📊 Summary:")
    total = 0
    for phase, tracks in SONGS.items():
        log_count = sum(1 for _, name in tracks if "LOG_" in name)
        song_count = len(tracks) - log_count
        total += len(tracks)
        print(f"  {phase}: {len(tracks)} total ({song_count} songs + {log_count} LOG entries)")
    
    print(f"\n✅ Total: {total} tracks organized")
    print("\n📌 Next steps:")
    print("   1. Copy actual audio files from temp_music into the song slots")
    print("   2. Replace .txt files for LOG entries with actual audio if available")
    print("   3. Upload the 365-releases/audio folder to Supabase storage")

if __name__ == "__main__":
    main()
