#!/bin/bash

# Script to organize 365 songs into phase-based directory structure
# Phase I: BOOT_SEQUENCE (Days 1-83)
# Phase II: CACHE_OVERFLOW (Days 84-187)
# Phase III: ROOT_ACCESS (Days 188-271)
# Phase IV: THE_CLOUD (Days 272-365)

set -e

# Configuration
TEMP_MUSIC="/Volumes/extremeUno/temp_music"
OUTPUT_BASE="365-releases/audio"
PHASE_CONFIG=(
  "1:83:january:BOOT_SEQUENCE"
  "84:187:february-march:CACHE_OVERFLOW"
  "188:271:april-june:ROOT_ACCESS"
  "272:365:july-december:THE_CLOUD"
)

echo "🎵 Starting music organization script..."
echo "Source: $TEMP_MUSIC"
echo "Output: $OUTPUT_BASE"
echo ""

# Create output directories
for config in "${PHASE_CONFIG[@]}"; do
  IFS=':' read -r start end months phase <<< "$config"
  phase_dir="$OUTPUT_BASE/$phase"
  mkdir -p "$phase_dir"
  echo "Created: $phase_dir"
done

# Get list of music files from temp folder
declare -A song_list=(
  # BOOT_SEQUENCE (Days 1-83)
  [1]="Were Going Crazy World"
  [2]="Shhh Bitch"
  [3]="You Like Steve Earle"
  [4]="Were Only Humanmd7"
  [5]="Swooped COUPE"
  [6]="Ss Take One"
  [7]="Devour"
  [8]="Poetry"
  [9]="Without You"
  [10]="PERMISSION_DENIED [LOG_108]"
  [11]="Getting Better"
  [12]="LANDR Want It Any Other Way Open Low"
  [13]="Dashboard of Life"
  [14]="Undercoa 4"
  [15]="What Bryan Was Working on Last"
  [16]="Prevail Scriber"
  [17]="What It Is"
  [18]="Goods 4 Me"
  [19]="Through the Ringer"
  [20]="Figures"
  [21]="Highup"
  [22]="REBOOT_SEQUENCE [LOG_109]"
  [23]="Come on Dance"
  [24]="Be Here Boo"
  [25]="Grenada"
  [26]="Brave"
  [27]="Talkin Nody"
  [28]="LANDR Smoothie Balanced Medium"
  [29]="Cursed 2ndmix"
  [30]="To Be a Man"
  [31]="Scars in My Mind"
  [32]="Whatuwant"
  [33]="Bettersion of Me"
  [34]="Consation W"
  [35]="The Light"
  [36]="404_SOUL_NOT_FOUND [LOG_101]"
  [37]="Camebackaroudnd"
  [38]="Eco N Time"
  [39]="Up All Night"
  [40]="Way Eight Fore Dat Storm Level"
  [41]="Be Nuter"
  [42]="Xzibit Forever"
  [43]="Pit What I Got"
  [44]="Not Good Enough"
  [45]="LANDR a Way Out Mas Balanced Medium"
  [46]="Mikeym"
  [47]="Filthy"
  [48]="Unforgettable"
  [49]="Dreams Again"
  [50]="DAEMON_RUNNING [LOG_102]"
  [51]="Change Perception"
  [52]="Bitter Better"
  [53]="The End"
  [54]="Tryied"
  [55]="Tried N True"
  [56]="Can't Go Back"
  [57]="Momentofexctasy"
  [58]="Awaits"
  [59]="Reality"
  [60]="Moment of Exctasy"
  [61]="Re"
  [62]="Friendzone"
  [63]="Never Ends"
  [64]="CONNECTION_RESET [LOG_100]"
  [65]="Untied"
  [66]="Luckyland"
  [67]="Letitgo"
  [68]="From the Earth to the Sea Flipped Mask"
  [69]="Save Tonight"
  [70]="Sau"
  [71]="A Girl"
  [72]="Isitthathard"
  [73]="Kurtcobain"
  [74]="Low Life"
  [75]="PING_TIMEOUT [LOG_106]"
  [76]="Benefits Me"
  [77]="Rabbit Hole"
  [78]="Choppmed of F Ya Feel Rough"
  [79]="Lightburst"
  [80]="Monetary"
  [81]="Get Ghost"
  [82]="ADMIN_ACCESS_REQUIRED [LOG_107]"
  [83]="Jacy B"
)

echo "✅ Script structure created"
echo ""
echo "Next steps:"
echo "1. Manually copy files from $TEMP_MUSIC to the phase directories"
echo "2. For ERROR songs, create placeholder files with [LOG_XXX] pattern"
echo "3. Files should be named as: NN - Song Name.mp3"
echo ""
echo "Phase mapping:"
echo "  Days 1-83   → $OUTPUT_BASE/BOOT_SEQUENCE"
echo "  Days 84-187 → $OUTPUT_BASE/CACHE_OVERFLOW"
echo "  Days 188-271 → $OUTPUT_BASE/ROOT_ACCESS"
echo "  Days 272-365 → $OUTPUT_BASE/THE_CLOUD"
